# README

## Title 
Mathematical models of avian influenza virus transmission and fatal outcome risk in humans

---

## Summary
This repository contains the code, output, and data for Joshua Mack's MSc thesis. 

---

### File descriptions

## Chapter_2
This folder contains the code and outputs for Chapter 2: Estimating the infection fatality ratio of zoonotic avian influenza viruses with pandemic potential using an evolutionary epidemiological model
---

### Chapter_2_Code
The `Chapter_2_Code/` directory contains the following scripts:
- `Interpandemic_periods.R`: Models the interpandemic period distributions
- `IFR.R`: Estimates the annual number of human AIV infections and the infection fatality ratio
- `Pandemic_delay.R`: Estimates the effect of preventing AIV spillovers on pandemic delay time
- `Spillover_comparison.R`: Compares estimated number of zoonotic spillovers with Day et al.,2006
- `Parameter_sensitivity.R`: Parameter sensitivity analysis
- `Genotype_sensitivity.R`: Genotype sensitivity analysis
- `Pandemic_sensitivity.R`: Pandemic sensitivity analysis
- `Reporting_sensitivity.R`: Death reporting sensitivity analysis
- `Mechanistic_boundary.R`: Mechanistic boundary analysis


### Chapter_2_Ouput
The `Chapter_2_Output/` directory contains output files:
- `mean_nh_38.csv`, `mean_nh_53.5.csv`, `mean_nh_18.8.csv`
- `transformed_samples_38.csv`, `transformed_samples_53.5.csv`, `transformed_samples_18.8.csv`
- `Parameter_sensitivity.csv`, `Genotype_sensitivity.csv`, `Pandemic_sensitivity.csv`, `Reporting_sensitivity.csv`, `Mechanistic_boundary.csv`

---

## Chapter 3
This folder contains the code and data used for Chapter 3: Estimating the time-varying transmission rate of highly pathogenic avian influenza virus in Newfoundland seabirds using a SEIRD model 

---

### Chapter_3_Code
The `Chapter_3_Code/` directory contains the following scripts:
- `NFLD.R`: Spatial distribution of seabird mortality associated with the 2022 HPAI virus outbreak
- `Delay_distribution.R`: Negative binomial delay distribution for Northern Gannet aerial survey observations
- `Data_interpolation.R`: Aggregation and linear interpolation of cumulative mortality observations to produce daily mortality time series for SEIRD model fitting
- `SEIRD.R`: SEIRD model for the spread of HPAI virus in Newfoundland seabirds
- `SEIRD_underreporting.R`: SEIRD model for the spread of HPAI virus in Newfoundland seabirds with underreporting scenarios
- `Connectivity_matrix.R`: Inter-patch connectivity matrix
- `Labrador.R`: Proposed patches for Labrador

### Chapter_3_Data
The `Chapter_3_Data/` directory contains the following files:
- `Data S1. Reported mortalities and morbidities in eastern Canada 2022.csv`: Reported wild bird mortalities and morbidities associated with the 2022 HPAI virus outbreak in eastern Canada
- `Important Bird and Biodiversity Areas of Canada Zones importantes pour la conservation des oiseaux et de la biodiversité du Can.kml`: Spatial boundaries of Important Bird and Biodiversity Areas used for mapping and patch delineation
- `NFLD_mortalities_7patch_with_backdistributed_gannets_NB.csv`: Newfoundland and Labrador seabird mortality dataset used for SEIRD model fitting, including negative binomial delay distribution for Northern Gannet aerial survey observations
- `dat.rds`: Daily interpolated cumulative mortality dataset generated by `Data_interpolation.R` and used as input for the SEIRD models
- `fitted_data.rds`: Fitted data from SEIRD model
- `fitted_data_undereporting.rds`: Fitted data from SEIRD model with undereporting scenarios

---

## Instructions to run the software for Chapter 2
1. Install R version 4.4.1.
2. Install required R packages listed above.
3. Set the working directory to the repository root.
4. Run the scripts in the following order:
   - `Interpandemic_periods.R`
   - `IFR.R`
   - `Pandemic_delay.R`
   - `Spillover_comparison.R`
   - `Parameter_sensitivity.R`
   - `Genotype_sensitivity.R`
   - `Pandemic_sensitivity.R`
   - `Reporting_sensitivity.R`
   - `Mechanistic_boundary.R`
   
---

## Instructions to run the software for Chapter 3
1. Install R version 4.4.1.
2. Install required R packages listed above.
3. Set the working directory to the repository root.
4. Ensure the required data files are present in the `Data/` directory (see File descriptions for full list of data files).
5. Run the scripts in the following order:
   - `NFLD.R`
   - `Delay_distribution.R`
   - `Data_interpolation.R`
   - `SEIRD.R`
   - `Connectivity_matrix.R`
   - `Labrador.R`

---

### Code version
- R version 4.4.1

---

### Packages versions
- patchwork (1.3.2)
- dplyr (1.1.4)
- ggplot2 (4.0.1)
- ggtext (0.1.2)
- scales (1.4.0)
- ggrepel (0.9.6)
- grid (4.4.1)
- lhs (1.2.0)
- sensitivity (1.30.2)
- triangle (1.0)
- bbmle (1.0.25.1)
- lubridate (1.9.4)
- ggridges (0.5.7)
- here (1.0.2)
- sf (1.0.23)
- macpan2 (3.5.1)
- tidyverse (2.0.0)
- zoo (1.8.14)
- stringr (1.6.0)
- splines (4.4.1)
- viridis (0.6.5)
- ggspatial (1.1.10)
- rnaturalearth (1.1.0)
- rnaturalearthdata (1.0.0.9000)
- rnaturalearthhires (1.0.0.9000)
- gganimate (1.0.11)
- gifski (1.32.0.2)
- transformr (0.1.5)
- cowplot (1.2.0)
- cli (3.6.5.9000)
- purrr (1.2.0)
- geosphere (1.6.5)
- reshape2 (1.4.5)
- lme4 (1.1-38)
- shellpipes (0.1.0)